### ISSUE TITLE
Currupted image

### ISSUE THREAD

**Issue by MatrixCoder0101** [mayank0274/acode-plugin-codesnap#1]
![Screenshot_2023-11-09-11-18-27-20_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/mayank0274/acode-plugin-codesnap/assets/101377369/2f8acf64-f78e-42c7-a852-c853fe0b0776)

**Please Fix this issue**
_The Saved Image file save is currupted_

**Comment by mayank0274** [comment]
are you trying to save image in termux storage ? 
save in device internal storage there its working properly

**Comment by MatrixCoder0101** [comment]
> are you trying to save image in termux storage ? 
> save in device internal storage there its working properly 

Same Problem

**Comment by mayank0274** [comment]
please tell your os and its version, because it working fine to me, if possible share a screen recording

**Comment by shaikhahemad** [comment]
I will also face this problem

**Comment by shaikhahemad** [comment]
My os is Android 13

**Comment by mayank0274** [comment]
> My os is Android 13

update to v1.0.1
-> download eruda console plugin
-> after click on save button in code snap plugin  check is ``` blob ``` logs on console or not ?

**Comment by MatrixCoder0101** [comment]
> > My os is Android 13
> 
> update to v1.0.1
> -> download eruda console plugin
> -> after click on save button in code snap plugin  check is ``` blob ``` logs on console or not ?

![Screenshot_2023-11-21-18-43-22-18_a2cf8efcdd42a8e6f7906303f104fb67.jpg](https://github.com/mayank0274/acode-plugin-codesnap/assets/101377369/2255688b-9a79-40c8-91d1-b95fe72c61cb)

**Comment by jaraaaraa** [comment]
no solution?

**Comment by Hamy9511** [comment]
I need help, i have de same problem

**Comment by APdev93** [comment]
I can resolve this

**Comment by mayank0274** [comment]
fixed in [this pr by raunak raj](https://github.com/mayank0274/acode-plugin-codesnap/pull/7)
