### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by shaikhahemad** [mayank0274/acode-plugin-codesnap#2]
![Screenshot_2023-11-20-20-57-34-03_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/mayank0274/acode-plugin-codesnap/assets/102429872/7def3c87-be48-4142-b108-359ce14d5d80)

Make code editor name user defined

**Comment by mayank0274** [comment]
added in v1.0.1 , click on default text "code editor" to edit it
