### ISSUE TITLE
Problem  with image 

### ISSUE THREAD

**Issue by elias0esmail** [mayank0274/acode-plugin-codesnap#3]
![Screenshot_20231127-130816_Gallery](https://github.com/mayank0274/acode-plugin-codesnap/assets/131258645/6cda0fc9-2ac1-4373-a162-5b20e31a35c1)

**Comment by mayank0274** [comment]
fixed in [this pr by raunak raj](https://github.com/mayank0274/acode-plugin-codesnap/pull/7)
