### ISSUE TITLE
Corrupted Image on Android 11+

### ISSUE THREAD

**Issue by bajrangCoder** [mayank0274/acode-plugin-codesnap#6]
This plugin is not able to save images on Android 11, 12, 13 because of change fs APIs , 
Some how I have implemented a solution which will save the buffer instead of blob and it's working, Soon I will pr it.

Note: I have changed `dom-to-image` to `html2canvas` because dom-to-image is outdated

**Comment by mayank0274** [comment]
fixed in [this pr by raunak raj](https://github.com/mayank0274/acode-plugin-codesnap/pull/7)
